### ISSUE TITLE
CalBox is changing current date when navigating next/prev month, but not highlighting it.

### ISSUE THREAD

**Issue by slavap** [jtsage/jtsage-datebox#356]
Example: user selected 11/29, it's highlighted. Then pressed next month. Selected date changed automatically to 11/30 and December is shown (datebox('getTheDate') returns 11/30), but this new selected date is not highlighted, which looks confusing for user. Inline mode.

UPDATE: displayed date in container remains unchanged (selected by user), but datebox('getTheDate') returns chaotic results when navigating by prev/next months. It should return date selected by user all the time and restore highlighting when returned to the month started from.

**Comment by jtsage** [comment]
Reopening for v5.0.0

**Comment by jtsage** [comment]
Re-closing, opened a couple new issues to make sure all of this made it in.
