### ISSUE TITLE
flipBox : kinetic rollers.

### ISSUE THREAD

**Issue by alexandredumat** [jtsage/jtsage-datebox#403]
Rather an enhancement.

The roll of flip boxes could be improved in 2 ways :
> When rolling the hours/min/... there could be inertia effect after touchend
> When the hours/min/... are changed the roll jumps to the given value, it would be better if it rolled smoothly from where it is.

**Comment by jtsage** [comment]
Hah.  You just beat me to adding an issue for this.  Started at cfd95ef8354f39ba2bff4025b239b26040f77d5f

Needs a lot of testing, and yes, "grid snapping" is on the list.

**Comment by jtsage** [comment]
This is pretty clean these days, and about as acurate as I can make it.

Perhaps play about with [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to make computation of the height of each element even more acurate? The CSS / jQuery values are sometimes only close.
