### ISSUE TITLE
I get an Error called "a.widget is not a function"

### ISSUE THREAD

**Issue by omeiths** [jtsage/jtsage-datebox#419]
Hi , 
I#m using Bootstrap 4.0 and get the following Error

>  Uncaught TypeError: a.widget is not a function
> at jtsage-datebox.min.js:2
> at jtsage-datebox.min.js:4

what am I doing wrong ?

**Comment by jtsage** [comment]
Hmm.  yeah, I notice that the install docs don't include a needed prerequisite.  The widget library from jqueryui is needed.

     <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

I'll get the docs updated, I thought it was in there, but it clearly isn't.

**Comment by AliNaik** [comment]
Uncaught TypeError: Cannot read property 'query' of undefined
