### ISSUE TITLE
Dialog Box outside from window

### ISSUE THREAD

**Issue by kveldscholten** [jtsage/jtsage-datebox#420]
There a option that aligns the box from left if there is not enough space from right to left?

![zwischenablage03](https://user-images.githubusercontent.com/5719257/35876826-cd48dd9e-0b73-11e8-88b1-0b4677fc5501.jpg)

**Comment by jtsage** [comment]
Which version?  Is this bootstrap4 by chance?  Because I think the alignment stuff isn't / wasn't ready last I was working on this.  If it's not bootstrap4, let me know, and I'll track down why this is happening.

Thanks.

**Comment by kveldscholten** [comment]
Is use it with Bootstrap v3.3.7

**Comment by jtsage** [comment]
Yes, there is an option:

http://dev.jtsage.com/DateBox/api/bootstrapDropdownRight/

It's poorly documented, but set it to "false", and it will hug the left side of the input, overflowing on the right as needed.
