### ISSUE TITLE
Support for font awesome 5 for jtsage-datebox Bootstrap 4

### ISSUE THREAD

**Issue by georges49** [jtsage/jtsage-datebox#422]
Hi, I am trying to use this awesome library in my website.

I am using Bootstrap 4 so I downloaded the Bootstrap 4 version of this library.

But the problem is that I am using font awesome 5 and the Bootstrap 4 version supports font awesome 4. So I have to use both font awesome 4 and font awesome 5 which is not ideal.

Is there any modifications I could do to make the font awesome 5 works? If not will we have font awesome 5 support soon?

Btw I am using the Date Box mode.

**Comment by georges49** [comment]
BTW, this what I get if I include both font awesome 4 and font awesome 5

<img width="585" alt="screen shot 2018-02-24 at 3 00 32 pm" src="https://user-images.githubusercontent.com/17703137/36630728-c2d5fffa-1973-11e8-8600-28c21b4b246a.png">

But If I remove font awesome 5, everything works fine

<img width="380" alt="screen shot 2018-02-24 at 3 00 51 pm" src="https://user-images.githubusercontent.com/17703137/36630740-fa1bb5d6-1973-11e8-929c-a7de82ea83ad.png">

But obviously I can't do that because I am using it in other pages

**Comment by jtsage** [comment]
I'm behind the times, didn't know they dropped version 5.  Yeah, it actually should be rather a simple change, lemme dig a bit in the next few days.  Fwiw, it might be worth experimenting with the "shim" they made too, dunno.  But a real solution is pending.

**Comment by georges49** [comment]
@jtsage Thanks for the reply.
Any updates on this?

**Comment by jtsage** [comment]
Hmm.  any update from you?  Updated the bootstrap version to like the latest 4.0.0 bootstrap, and dumped the latest fontawesome.  Looks right to me, maybe you did something else to get this?  If so, and you can duplicate, I'd love to explore more.

http://dev.jtsage.com/jquery-mobile-datebox-dev/work/bootstrap4fa5.html

**Comment by jtsage** [comment]
Lies.  it doesn't look *bad*, but it also is not right.  I'll work on getting the changed names in there.

**Comment by georges49** [comment]
@jtsage After reading your comment, I tried something.
Initially I included font awesome 5 as SVG with JS
https://fontawesome.com/get-started/svg-with-js
As a result the style was messed up.

But when I included it as css
https://fontawesome.com/get-started
It worked fine.
