### ISSUE TITLE
Calbox - selected date is not highlighted when switching to next month, but highlighted when switching to previous month.

### ISSUE THREAD

**Issue by slavap** [jtsage/jtsage-datebox#425]
# April to May (bug):

![image](https://user-images.githubusercontent.com/4129763/39461122-86df867e-4cbd-11e8-81f2-d0cf93ab5eb8.png)
![image](https://user-images.githubusercontent.com/4129763/39461128-9180287c-4cbd-11e8-9958-104d2c9f5847.png)

# June to May (ok):

![image](https://user-images.githubusercontent.com/4129763/39461151-a6d2c4dc-4cbd-11e8-945e-5b25beba55b6.png)
![image](https://user-images.githubusercontent.com/4129763/39461163-afb21da0-4cbd-11e8-9480-2a7e0f6d6bc1.png)

**Comment by jtsage** [comment]
eww.  wierd.  looking at this.

**Comment by jtsage** [comment]
Huh.  This looks like you were on the main page of the documentation site. Just tried this, and I don't see it happening. 

So, I either fixed it (which I doubt, as I've done nothing).  

Or, it's something browser related (maybe). Local date based (maybe).  

I dunno.  Any help would be cool - OS / Browser / etc.

**Comment by slavap** [comment]
@jtsage It was not browser or locale related, I had tested it in Chrome and Firefox, and my locale is en_US.
I **cannot reproduce** it on http://dev.jtsage.com/DateBox/ anymore, so probably it's fixed collaterally :-)
I will try to update my project from 4.3.1 to the latest version, and let you know if the problem still exists.

**Comment by jtsage** [comment]
Cool.  thanks for taking the time.  

My fear is that it relates back to a the DST bug, which I kinda knew likely existed, and would crop up in odd ways - although the test dates *shouldn't* be affected.  

At any rate, not much to do until I / we can figure out how to get it to crop up again.

Thanks!

**Comment by jtsage** [comment]
This should be totally fixed in v5. I redid the theme calculations in a sane manner, rather than bolting them on way later.

**Comment by jtsage** [comment]
Yeah, lies, this was an outlier condition that I didn't handle in v5 yet.  It's absolutely fixed now., along with an option called "calSelectedOutOfBounds", defaulted to true, which means it will use the selected theme on out of bounds dates.
