### ISSUE TITLE
Download builder not working 502

### ISSUE THREAD

**Issue by gregh3269** [jtsage/jtsage-datebox#429]
Hello,

The download builder http://dev.jtsage.com/DateBox/builder/ replies with a 502 bad gateway?

Cheers Greg

**Comment by jtsage** [comment]
Yeah, this is fixed.  Apparently uglifyJS2 changed what was actually available via the API, and when I did a server upgrade, it upgraded too.  Long story short, fixed, re: 53e141f329832002281010fafd271790918b2e63
