### ISSUE TITLE
jqm Calbox with Theme roller does not show current date using ui-btn- syntax

### ISSUE THREAD

**Issue by gregh3269** [jtsage/jtsage-datebox#430]
Hello,

I am using the jqm theme roller for styling, I have two themes a and b with minor differences mainly with the header.  When I call calbox it does not show the current date, I have tried using theme b (but is basically the same as theme a except for the header).  The element has the css set to ui-btn-b, to make it show I can add ui-btn-active so it does the reverse.

I have tried changing the colours using the theme roller but involves doing the who set (normal, hover, pressed, active), also I really did not want to upset other parts of the system using theme b.

Is there an easy way to add the ui-btn-active locally?

eg for date 28th:

```
<div class="ui-datebox-griddate ui-corner-all ui-btn ui-btn-a">26</div>
<div class="ui-datebox-griddate ui-corner-all ui-btn ui-btn-a">27</div>
<div class="ui-datebox-griddate ui-corner-all ui-btn ui-btn-b ui-btn-active">28</div>
<div class="ui-datebox-griddate ui-corner-all ui-btn ui-btn- ui-state-disabled">29</div>
```

Cheers Greg

**Comment by gregh3269** [comment]
...Sorry, worked it out,

"themeDateToday" : "b ui-btn-active" 

Guess its not exactly how it is supposed to be used, but it works ok.

Cheers Greg

**Comment by jtsage** [comment]
Yup, you are dead on there. Pretty much "themeDateToday" gets appended to "ui-btn-", so overloading it like that is a good way to do it.
