### ISSUE TITLE
Drop jQM support

### ISSUE THREAD

**Issue by jtsage** [jtsage/jtsage-datebox#432]
jQM hasn't had an update in a few years.  Supporting it is silly.

**Comment by slavap** [comment]
Could you please preserve the current version of documentation somewhere then? I still have large project based on jqm and though it’s ok to remain on ver4 of datebox, loosing documentation could be a problem.

**Comment by jtsage** [comment]
Of course, I'll make sure it doesn't go away anytime soon (or ever really) - nor would the built versions if your linking them in.  For what it's worth, I'm still at least a couple months away from being remotely ready with this.

I've not totally killed the idea of jQM in my mind either - if this works out the way I am hoping, support could be dropped in pretty quickly.  If anything, this is more of a way to re-write so its datebox first, then the framework - rather than currently it's kind of datebox, then jqm, then bolt on a different framework instead.

I'm only I broke one existing feature so far (and am reopening #356 to remind myself), but the theme settings got a major overhaul.

**Comment by slavap** [comment]
By the way, have you considered to use interface for generating actual layout and properties/attributes. That way it will be separate implementation class for each supported framework, and base code will be much more abstract and clean. Also switching to typescript could be a good idea.

**Comment by jtsage** [comment]
Pretty much, yeah. There's going to be theme definitions and a "styleFunctions" object in each framework file.

For instance, for the calbox grid, it asks

 - what encloses a grid
 - what encloses a row
 - what does each box get

Current working copy, and a good idea of where I'm going - also, with how this works, it's going to be a huge leverage point for folks such as yourself who have very specific requirements and are not afraid to fork their own version https://github.com/jtsage/jtsage-datebox/blob/v.next/src/js/framework/bootstrap4.js

I'm not at all familiar with typescript, gonna look into that.  

One of the big things I'd like to do is drop the need to load the jqueryui widget library (which jQM imported and altered slightly).  It's a ~20k chunk of code if I include it, or another HTTP request if I don't.

**Comment by slavap** [comment]
Typescript is superset of JavaScript, so you can start as is, and start using new features step by step.

**Comment by jtsage** [comment]
Closing as rejected.  

1.) jQM will get a build for v5.

2.) v4 will not be moving it's home on the web.  v5 is getting it's own subdomain, and v4 will get a banner notice in the docs that it is being phased out. (gonna branch it off in git too, so some bug fixes should still be possible)
