### ISSUE TITLE
CDN i18n excessive min.min.js

### ISSUE THREAD

**Issue by slavap** [jtsage/jtsage-datebox#437]
![image](https://user-images.githubusercontent.com/4129763/54470418-719e1d00-4764-11e9-8a3e-a5b40c6821c7.png)

**Comment by jtsage** [comment]
Huh.  wierd.  Must be something funky about the build process.  

I removed the doubles for now.  

Thanks for your attention, as always :)

As a side note, the new framework system is working out a lot better than I thought it would.  Keeping jQM in should not be impossible by any means.  The only real break API change then is going to be that some of the theme options are going to change names.  I'm still around a month away probably, and I'll make sure I do a real MIGRATION.md guide this time. (As discussed before, I'm gonna fork where on my server this hosts from, so I will leave the existing version & docs intact, just with a warning "this isn't the latest version" added to all the pages.

**Comment by slavap** [comment]
@jtsage Sounds good to me. By the way, themeInput should also work for calbox mode (currently it's not working), because it's quite often situation when input and popup calendar are styled completely different way.

**Comment by jtsage** [comment]
Re: the last comment.  Gutted / re-wrote the theme stuff.  Everything inside the control is discreetly addressed.

The original input is never touched, short of adding the button.  Which does not have a theme entry.  Damn. #450.

Closing, as the minifying was corrected, and the build script is now smart enough not to do it again.
