### ISSUE TITLE
Custom Download Builder builds version 4.4.1, though the latest is 4.4.2

### ISSUE THREAD

**Issue by slavap** [jtsage/jtsage-datebox#438]
/*
 * JTSage-DateBox
 * For: jqm; With: calbox
 * Date: 2019-03-16T04:02:51.765Z
 * http://dev.jtsage.com/DateBox/
 * https://github.com/jtsage/jquery-mobile-datebox
 *
 * Copyright 2010, 2019 JTSage. and other contributors
 * Released under the MIT license.
 * https://github.com/jtsage/jquery-mobile-datebox/blob/master/LICENSE.txt
 *
 */

(function($) {
    $.widget("jtsage.datebox", {
        initSelector: "input[data-role='datebox']",
        options: {
            version: "4.4.1",
            jqmVersion: "1.4.5",
            bootstrapVersion: "3.3.7",
            bootstrap4Version: "4.0.0",
            jqmuiWidgetVersion: "1.11.4",

**Comment by jtsage** [comment]
Bah.  crap.  Step #4354335 to a new version : restart the builder server process.

Fixed.

**Comment by slavap** [comment]
@jtsage Thanks, it works now.
