### ISSUE TITLE
Unintentionally dropped themeInput for datebox mode.  Put it back.

### ISSUE THREAD

**Issue by jtsage** [jtsage/jtsage-datebox#445]

**Comment by slavap** [comment]
@jtsage by the way, it would be nice to have themeInput working in calbox mode as well.

**Comment by jtsage** [comment]
Can do, although I'm not sure I totally follow.  You mean for the picker dropdowns if they appear?

**Comment by slavap** [comment]
@jtsage No, in version 4.4 if I want black (swatch B) input and white popup calendar (swatch A), I cannot do it out of the box, because swatch B is inherited by both (theme property). So it would be nice to specify two properties: themeInput and theme.

**Comment by jtsage** [comment]
oh, I understand. Yes, very much possible in the new version.  I'll put together a test page just to make sure.

**Comment by jtsage** [comment]
a/n: Option added back, needs documented.  Well, sort of.  Old option was very poorly named.

**Comment by slavap** [comment]
@jtsage thank you!

**Comment by jtsage** [comment]
Alrighty...  set up a demo for this.

themeInput was horribly named.  I'm only mostly sure what it was intended for anymore.  At any rate, for the original input on the page, you can theme it like any other input - jQM handles that bit, I just bolt on the open button.

Inside, every part of the control can be themed using the new system.  I didn't heavily comment, but most of the options used in the sample are pretty self explanatory.

https://jtsage.dev/jtsage-datebox-next/work/jqm-theme-acrobat.html

Final step for jQM is I'm nearly positive the positioning code isn't functioning as expected.  Gotta work through that.
