### ISSUE TITLE
set Calendar default day to tomorrow 

### ISSUE THREAD

**Issue by ttresslar** [jtsage/jtsage-datebox#476]
I am trying to set the default start date to be tomorrow instead of today. We are selling tickets, but the customer cannot buy tickets for today since the shuttles have already departed. I was able to black out today by setting notToday = true, but the default value is still today. There is no really easy way to do this with js, so it would be great to have this as a feature within datebox.

**Comment by jtsage** [comment]
Hmm.  As it happens, the defaultValue option is broken in the current build.  If it were not, you could actually do this via:

```js
defaultDate: new Date.adj(2,1)
```

but, not inline in the HTML.  have to do it using prototype options.

That said, I’m going to add:

```js
defaultDate: “+/-### of seconds”
```

This second one will work inline.  Gimme a couple hours to finish docs and push it live.

**Comment by jtsage** [comment]
SHA: 6e6700c5ca23f61a82b0c4807922f5def9d1e8aa

**Comment by jtsage** [comment]
Pushed in version 5.1.5

https://datebox.jtsage.dev/defaults/

**Comment by ttresslar** [comment]
Wow. Thanks for the quick reply! Looking forward to trying it out
