### ISSUE TITLE
Durationbox - minDur and MaxDur not setting limits

### ISSUE THREAD

**Issue by CapDev** [jtsage/jtsage-datebox#478]
Found after upgrading from 4.3.1 to latest 5.1.5.

Using jtsage-datebox.bootstrap.js for Bootstrap 3.4.1.

The limits set in minDur and maxDur are not respected in the Durationbox.

Values are set in seconds the same as for defaultValue.

Expect the time to stop at the limits set as previous version did.

Occurs in the Chrome browser version 77 on macOS.

Codepen of issue: https://codepen.io/CapDev/pen/RwwaRNq

Thanks.

**Comment by jtsage** [comment]
Huh.  Confirmed.  Doesn't look like it does anything.  

Best case, I can hit on this late this afternoon.

**Comment by jtsage** [comment]
Built 5.1.6 for -latest.  I'll build the full release later tonight.

**Comment by jtsage** [comment]
(as a side note, force-reload your codepen, it works now)

**Comment by CapDev** [comment]
Thanks for quick fix. I will test in development later today but yep it is working in the codepen.

**Comment by CapDev** [comment]
Working now in 5.1.6. Thanks
