### ISSUE TITLE
useTodayButton and usePlaceholder options not functioning correctly in calbox

### ISSUE THREAD

**Issue by CapDev** [jtsage/jtsage-datebox#479]
Found after upgrading from 4.3.1.

Using jtsage-datebox.bootstrap.js version 5.1.6 for Bootstrap 3.4.1.

Occurs in the Chrome browser version 77 on macOS.

Codepen of issues: https://codepen.io/CapDev/pen/ZEEWdWp

The useTodayButton option produces the opposite result as the api description.

"This button will "select" today, but it will not "set" today. It is for quick navigation."

Expect the "Jump to today" button to shift the calbox month to the current month but this does not occur and instead the date input is set to current date which is not expected.

The usePlaceholder option is only functioning when a simple html input label is used. If the label "for" attribute and the id for the calbox are the same then unexpected results occur. 

My datebox use is often within forms written in ruby where the label and datebox id will be the same and changing only the label to html complicates localization.

Also when the usePlaceholder option is allowed to work with a simple html label used, as shown in the codepen above, its value will be passed to the Header text in the calbox. I would expect this text to still be the label value.

Thanks for looking into this.  

Thanks.

**Comment by jtsage** [comment]
Thanks.  I'll look at this tonight.  I did roll .6 out to release, this will be .7

~j

**Comment by jtsage** [comment]
Re: placeholder.  

So, I think I understand your thoughts here - right now, if usePlaceholder is a string, that gets used as the header text.  You are saying that usePlaceholder shouldn't propegate that far, that the text inside &lt;label> should still be used?  And the usePlaceholder text should only be used at the placeholder (which is a bit implied by this option name I would admit).

I can certainly see the use case - I'm guessing you are translating the &lt;label> text and not the placeholder itself?

As for the useTodayButton behavior - yeah, that's not right. I can understand why I did it this way, but it's not even refreshing the display like it should.  I'll work on making it a true display jump instead of a set the date function.

**Comment by jtsage** [comment]
Oh, and if the &lt;label> has a correct "for" attribute, the usePlaceholder text gets ignored.  Or maybe overridden. Yeah, that's not intended.

**Comment by CapDev** [comment]
Yes I do not want the usePlaceholder string to overwrite the header text by default.

The placeholder text is sometimes set dynamically which is why using plain html inline is not suitable also.

Correct that the label text is translated in the form.

**Comment by jtsage** [comment]
Alrighty.  Makes sense.

Current order of precedence:

1. options.overrideDialogLabel
2. &lt;input> placeholder attr
3. &lt;input> title attr
4. &lt;label> text (with proper for attr)
5. i18n.titleDateDialogLabel / i18n.titleTimeDialogLabel (mode dependant)

So, here is my proposal:

New options, defaulting to true, to preserve what it has done, in order of precedence:

* __headerFollowsPlaceholder__ : when false, skip step 2 above
* __headerFollowsTitle__ : when false, skip step 3 above
* __headerFollowsLabel__ : when false, skip step 4 above.

So, your use case, you'd set "_headerFollowsPlaceholder: false_" (if title is empty, no need to explicitly ignore)

Thoughts?

**Comment by jtsage** [comment]
The commit above is a fix for the jump to today/tomorrow button.

**Comment by CapDev** [comment]
I agree with your proposal for the new options that will set the header text.

Tested your change the useTodayButton function and it is working as previously in 4.3.1 and how I had thought was intended. Thanks.

**Comment by jtsage** [comment]
Codepen of an example: https://codepen.io/jtsage/pen/abbZXKv

Built to -latest.  Gonna document it and give some test time then run the release (minor dot this time as this is presumably new functionality)

**Comment by CapDev** [comment]
The options in your codepen example works great. Will further test as I roll through updating my use in app. Thanks for sorting this so quickly.

**Comment by jtsage** [comment]
No worries.  I use such a limited set of these options in my own projects, always nice to hear from someone who is using more of them.  Fwiw, the quick turnaround is good for a couple more days, then $realJob is gonna take over for a week or two.
