### ISSUE TITLE
Durationbox: Manually entering Days, Hours, Mins, Seconds resets all other fields.

### ISSUE THREAD

**Issue by rickjmatthews** [jtsage/jtsage-datebox#487]
Manually entering Days, Hours, Mins, Seconds into the duration box resets all the other fields to 0. For example the only way to enter a duration of 1 hr and 30 mins is to use the + and - buttons. If you try and type this directly into the input boxes, the hours will reset to 0.

**Comment by jtsage** [comment]
Yeah.  I must have only tested with changing a field at a time, the logic here was never going to work.  Addressed in next release, about 30 min out.

**Comment by jtsage** [comment]
Ok, corrected.  5.3.1 build is up on my site, http://cdn.jtsage.com/jtsage-datebox/5.3.1/, and the cdnjs repos, and the download builder.

**Comment by rickjmatthews** [comment]
Fixed in under a week - What a star!

Many thanks.
