### ISSUE TITLE
5.3.1 is missing base option for blackDatesPeriod

### ISSUE THREAD

**Issue by CapDev** [jtsage/jtsage-datebox#489]
When opening a calbox there is the cannot read property '0' of undefined error.

This is coming from the blackDatesPeriod function and can be resolved by adding the following line within the options:

            blackDatesPeriod: false,

**Comment by jtsage** [comment]
dumb.  just a minute.  5.3.2 here we come.

**Comment by jtsage** [comment]
build and pushed to live site.  That's my bad - didn't crop up in testing, as I was testing just that feature, and it was of course set to something.

**Comment by CapDev** [comment]
That has fixed it. Thanks.
